/*
 * embedded_assets.c — Generated file mapping URL paths to embedded bytes.
 * DO NOT EDIT — regenerated by scripts/embed-frontend.sh
 */
#include "ui/embedded_assets.h"
#include <string.h>

extern const unsigned char _binary_assets_abnfDiagram_VRR7QNED__c_2PTVo_js_start[];
extern const unsigned char _binary_assets_abnfDiagram_VRR7QNED__c_2PTVo_js_end[];
extern const unsigned char _binary_assets_arc_C3M3wQW8_js_start[];
extern const unsigned char _binary_assets_arc_C3M3wQW8_js_end[];
extern const unsigned char _binary_assets_architectureDiagram_ZJ3FMSHR_F6b7AjI6_js_start[];
extern const unsigned char _binary_assets_architectureDiagram_ZJ3FMSHR_F6b7AjI6_js_end[];
extern const unsigned char _binary_assets_blockDiagram_677ZJIJ3_BRs5fZRQ_js_start[];
extern const unsigned char _binary_assets_blockDiagram_677ZJIJ3_BRs5fZRQ_js_end[];
extern const unsigned char _binary_assets_c4Diagram_LMCZKHZV_CIkMNFUy_js_start[];
extern const unsigned char _binary_assets_c4Diagram_LMCZKHZV_CIkMNFUy_js_end[];
extern const unsigned char _binary_assets_channel_KI9yzJ2z_js_start[];
extern const unsigned char _binary_assets_channel_KI9yzJ2z_js_end[];
extern const unsigned char _binary_assets_chunk_2Q5K7J3B_CBANiLPS_js_start[];
extern const unsigned char _binary_assets_chunk_2Q5K7J3B_CBANiLPS_js_end[];
extern const unsigned char _binary_assets_chunk_32BRIVSS_Dl_O1X_9_js_start[];
extern const unsigned char _binary_assets_chunk_32BRIVSS_Dl_O1X_9_js_end[];
extern const unsigned char _binary_assets_chunk_5VM5RSS4_CrsYnroW_js_start[];
extern const unsigned char _binary_assets_chunk_5VM5RSS4_CrsYnroW_js_end[];
extern const unsigned char _binary_assets_chunk_EX3LRPZG_CSLHLFEq_js_start[];
extern const unsigned char _binary_assets_chunk_EX3LRPZG_CSLHLFEq_js_end[];
extern const unsigned char _binary_assets_chunk_JWPE2WC7_BuYoJmxh_js_start[];
extern const unsigned char _binary_assets_chunk_JWPE2WC7_BuYoJmxh_js_end[];
extern const unsigned char _binary_assets_chunk_MOJQB5TN_9L_iz3VC_js_start[];
extern const unsigned char _binary_assets_chunk_MOJQB5TN_9L_iz3VC_js_end[];
extern const unsigned char _binary_assets_chunk_RYQCIY6F_D6X7TqLO_js_start[];
extern const unsigned char _binary_assets_chunk_RYQCIY6F_D6X7TqLO_js_end[];
extern const unsigned char _binary_assets_chunk_V7JOEXUC_Yo1_V0uS_js_start[];
extern const unsigned char _binary_assets_chunk_V7JOEXUC_Yo1_V0uS_js_end[];
extern const unsigned char _binary_assets_chunk_VR4S4FIN_awYWJFZo_js_start[];
extern const unsigned char _binary_assets_chunk_VR4S4FIN_awYWJFZo_js_end[];
extern const unsigned char _binary_assets_chunk_XXDRQBXY_D7pYMXfx_js_start[];
extern const unsigned char _binary_assets_chunk_XXDRQBXY_D7pYMXfx_js_end[];
extern const unsigned char _binary_assets_classDiagram_OUVF2IWQ_ChzQG6bQ_js_start[];
extern const unsigned char _binary_assets_classDiagram_OUVF2IWQ_ChzQG6bQ_js_end[];
extern const unsigned char _binary_assets_classDiagram_v2_EOCWNBFH_ChzQG6bQ_js_start[];
extern const unsigned char _binary_assets_classDiagram_v2_EOCWNBFH_ChzQG6bQ_js_end[];
extern const unsigned char _binary_assets_cose_bilkent_JH36ORCC_Cg1Tn6Ix_js_start[];
extern const unsigned char _binary_assets_cose_bilkent_JH36ORCC_Cg1Tn6Ix_js_end[];
extern const unsigned char _binary_assets_cynefinDiagram_TSTJHNR4_Dqx3MYSd_js_start[];
extern const unsigned char _binary_assets_cynefinDiagram_TSTJHNR4_Dqx3MYSd_js_end[];
extern const unsigned char _binary_assets_cynefin_VYW2F7L2_BSmXNjHD_js_start[];
extern const unsigned char _binary_assets_cynefin_VYW2F7L2_BSmXNjHD_js_end[];
extern const unsigned char _binary_assets_cytoscape_esm_DTSO7Bv0_js_start[];
extern const unsigned char _binary_assets_cytoscape_esm_DTSO7Bv0_js_end[];
extern const unsigned char _binary_assets_dagre_VKFMJZFB_Dc8OyQR__js_start[];
extern const unsigned char _binary_assets_dagre_VKFMJZFB_Dc8OyQR__js_end[];
extern const unsigned char _binary_assets_defaultLocale_DX6XiGOO_js_start[];
extern const unsigned char _binary_assets_defaultLocale_DX6XiGOO_js_end[];
extern const unsigned char _binary_assets_diagram_FQU43EPY_BAjgu_57_js_start[];
extern const unsigned char _binary_assets_diagram_FQU43EPY_BAjgu_57_js_end[];
extern const unsigned char _binary_assets_diagram_G47NLZAW_D55Isr_m_js_start[];
extern const unsigned char _binary_assets_diagram_G47NLZAW_D55Isr_m_js_end[];
extern const unsigned char _binary_assets_diagram_NH7WQ7WH_DNd0VJ_m_js_start[];
extern const unsigned char _binary_assets_diagram_NH7WQ7WH_DNd0VJ_m_js_end[];
extern const unsigned char _binary_assets_diagram_OA4YK3LP_DgyAjoFf_js_start[];
extern const unsigned char _binary_assets_diagram_OA4YK3LP_DgyAjoFf_js_end[];
extern const unsigned char _binary_assets_diagram_WEI45ONY_rJ2jqWd2_js_start[];
extern const unsigned char _binary_assets_diagram_WEI45ONY_rJ2jqWd2_js_end[];
extern const unsigned char _binary_assets_ebnfDiagram_CCIWWBDH_Cgd4_fJ7_js_start[];
extern const unsigned char _binary_assets_ebnfDiagram_CCIWWBDH_Cgd4_fJ7_js_end[];
extern const unsigned char _binary_assets_erDiagram_Q63AITRT_CWuotk_y_js_start[];
extern const unsigned char _binary_assets_erDiagram_Q63AITRT_CWuotk_y_js_end[];
extern const unsigned char _binary_assets_flowDiagram_23GEKE2U_2cZ1_br__js_start[];
extern const unsigned char _binary_assets_flowDiagram_23GEKE2U_2cZ1_br__js_end[];
extern const unsigned char _binary_assets_ganttDiagram_NO4QXBWP_B9vgELs0_js_start[];
extern const unsigned char _binary_assets_ganttDiagram_NO4QXBWP_B9vgELs0_js_end[];
extern const unsigned char _binary_assets_gitGraphDiagram_IHSO6WYX_ClXJiEjU_js_start[];
extern const unsigned char _binary_assets_gitGraphDiagram_IHSO6WYX_ClXJiEjU_js_end[];
extern const unsigned char _binary_assets_graph_C9eacEi8_js_start[];
extern const unsigned char _binary_assets_graph_C9eacEi8_js_end[];
extern const unsigned char _binary_assets_index_B4D0ZKgB_css_start[];
extern const unsigned char _binary_assets_index_B4D0ZKgB_css_end[];
extern const unsigned char _binary_assets_index_BWsasQSj_js_start[];
extern const unsigned char _binary_assets_index_BWsasQSj_js_end[];
extern const unsigned char _binary_assets_infoDiagram_FWYZ7A6U_Cq3vOebR_js_start[];
extern const unsigned char _binary_assets_infoDiagram_FWYZ7A6U_Cq3vOebR_js_end[];
extern const unsigned char _binary_assets_init_Gi6I4Gst_js_start[];
extern const unsigned char _binary_assets_init_Gi6I4Gst_js_end[];
extern const unsigned char _binary_assets_ishikawaDiagram_FXEZZL3T_BVqTp7p5_js_start[];
extern const unsigned char _binary_assets_ishikawaDiagram_FXEZZL3T_BVqTp7p5_js_end[];
extern const unsigned char _binary_assets_journeyDiagram_5HDEW3XC_DkuAasZQ_js_start[];
extern const unsigned char _binary_assets_journeyDiagram_5HDEW3XC_DkuAasZQ_js_end[];
extern const unsigned char _binary_assets_kanban_definition_HUTT4EX6_B1_0DUb__js_start[];
extern const unsigned char _binary_assets_kanban_definition_HUTT4EX6_B1_0DUb__js_end[];
extern const unsigned char _binary_assets_katex_C5jXJg4s_js_start[];
extern const unsigned char _binary_assets_katex_C5jXJg4s_js_end[];
extern const unsigned char _binary_assets_layout_DEXfKzaS_js_start[];
extern const unsigned char _binary_assets_layout_DEXfKzaS_js_end[];
extern const unsigned char _binary_assets_linear_nyeScZjw_js_start[];
extern const unsigned char _binary_assets_linear_nyeScZjw_js_end[];
extern const unsigned char _binary_assets_map_Czzmt4hB_js_start[];
extern const unsigned char _binary_assets_map_Czzmt4hB_js_end[];
extern const unsigned char _binary_assets_mindmap_definition_LN4V7U3C_CRSf194R_js_start[];
extern const unsigned char _binary_assets_mindmap_definition_LN4V7U3C_CRSf194R_js_end[];
extern const unsigned char _binary_assets_ordinal_Cboi1Yqb_js_start[];
extern const unsigned char _binary_assets_ordinal_Cboi1Yqb_js_end[];
extern const unsigned char _binary_assets_pegDiagram_2B236MQR_BcO2h6Jx_js_start[];
extern const unsigned char _binary_assets_pegDiagram_2B236MQR_BcO2h6Jx_js_end[];
extern const unsigned char _binary_assets_pieDiagram_ENE6RG2P_BuSjvKsW_js_start[];
extern const unsigned char _binary_assets_pieDiagram_ENE6RG2P_BuSjvKsW_js_end[];
extern const unsigned char _binary_assets_quadrantDiagram_ABIIQ3AL_DYIHCjpZ_js_start[];
extern const unsigned char _binary_assets_quadrantDiagram_ABIIQ3AL_DYIHCjpZ_js_end[];
extern const unsigned char _binary_assets_railroadDiagram_RFXS5EU6_TyxOBVs6_js_start[];
extern const unsigned char _binary_assets_railroadDiagram_RFXS5EU6_TyxOBVs6_js_end[];
extern const unsigned char _binary_assets_requirementDiagram_TGXJPOKE_DK7YXeJM_js_start[];
extern const unsigned char _binary_assets_requirementDiagram_TGXJPOKE_DK7YXeJM_js_end[];
extern const unsigned char _binary_assets_sankeyDiagram_HTMAVEWB_mWQtOzDn_js_start[];
extern const unsigned char _binary_assets_sankeyDiagram_HTMAVEWB_mWQtOzDn_js_end[];
extern const unsigned char _binary_assets_sequenceDiagram_DBY2YBRQ_BZbYj7tV_js_start[];
extern const unsigned char _binary_assets_sequenceDiagram_DBY2YBRQ_BZbYj7tV_js_end[];
extern const unsigned char _binary_assets_sizeCapture_X5ZJPWSS_DRWwrWzE_js_start[];
extern const unsigned char _binary_assets_sizeCapture_X5ZJPWSS_DRWwrWzE_js_end[];
extern const unsigned char _binary_assets_stateDiagram_2N3HPSRC_LENvSDk0_js_start[];
extern const unsigned char _binary_assets_stateDiagram_2N3HPSRC_LENvSDk0_js_end[];
extern const unsigned char _binary_assets_stateDiagram_v2_6OUMAXLB_CGvSjJgt_js_start[];
extern const unsigned char _binary_assets_stateDiagram_v2_6OUMAXLB_CGvSjJgt_js_end[];
extern const unsigned char _binary_assets_swimlanes_5IMT3BWC_Dlb7vtlK_js_start[];
extern const unsigned char _binary_assets_swimlanes_5IMT3BWC_Dlb7vtlK_js_end[];
extern const unsigned char _binary_assets_swimlanesDiagram_G3AALYLV_CN7h3I3y_js_start[];
extern const unsigned char _binary_assets_swimlanesDiagram_G3AALYLV_CN7h3I3y_js_end[];
extern const unsigned char _binary_assets_timeline_definition_FHXFAJF6_0O92i0Jd_js_start[];
extern const unsigned char _binary_assets_timeline_definition_FHXFAJF6_0O92i0Jd_js_end[];
extern const unsigned char _binary_assets_vennDiagram_L72KCM5P_CMpVF7tE_js_start[];
extern const unsigned char _binary_assets_vennDiagram_L72KCM5P_CMpVF7tE_js_end[];
extern const unsigned char _binary_assets_wardleyDiagram_EHGQE667__1au6CfY_js_start[];
extern const unsigned char _binary_assets_wardleyDiagram_EHGQE667__1au6CfY_js_end[];
extern const unsigned char _binary_assets_xychartDiagram_FW5EYKEG_BUn214Ut_js_start[];
extern const unsigned char _binary_assets_xychartDiagram_FW5EYKEG_BUn214Ut_js_end[];
extern const unsigned char _binary_index_html_start[];
extern const unsigned char _binary_index_html_end[];

cbm_embedded_file_t CBM_EMBEDDED_FILES[] = {
    {"/assets/abnfDiagram-VRR7QNED--c_2PTVo.js", _binary_assets_abnfDiagram_VRR7QNED__c_2PTVo_js_start, 0, "application/javascript"},
    {"/assets/arc-C3M3wQW8.js", _binary_assets_arc_C3M3wQW8_js_start, 0, "application/javascript"},
    {"/assets/architectureDiagram-ZJ3FMSHR-F6b7AjI6.js", _binary_assets_architectureDiagram_ZJ3FMSHR_F6b7AjI6_js_start, 0, "application/javascript"},
    {"/assets/blockDiagram-677ZJIJ3-BRs5fZRQ.js", _binary_assets_blockDiagram_677ZJIJ3_BRs5fZRQ_js_start, 0, "application/javascript"},
    {"/assets/c4Diagram-LMCZKHZV-CIkMNFUy.js", _binary_assets_c4Diagram_LMCZKHZV_CIkMNFUy_js_start, 0, "application/javascript"},
    {"/assets/channel-KI9yzJ2z.js", _binary_assets_channel_KI9yzJ2z_js_start, 0, "application/javascript"},
    {"/assets/chunk-2Q5K7J3B-CBANiLPS.js", _binary_assets_chunk_2Q5K7J3B_CBANiLPS_js_start, 0, "application/javascript"},
    {"/assets/chunk-32BRIVSS-Dl-O1X_9.js", _binary_assets_chunk_32BRIVSS_Dl_O1X_9_js_start, 0, "application/javascript"},
    {"/assets/chunk-5VM5RSS4-CrsYnroW.js", _binary_assets_chunk_5VM5RSS4_CrsYnroW_js_start, 0, "application/javascript"},
    {"/assets/chunk-EX3LRPZG-CSLHLFEq.js", _binary_assets_chunk_EX3LRPZG_CSLHLFEq_js_start, 0, "application/javascript"},
    {"/assets/chunk-JWPE2WC7-BuYoJmxh.js", _binary_assets_chunk_JWPE2WC7_BuYoJmxh_js_start, 0, "application/javascript"},
    {"/assets/chunk-MOJQB5TN-9L-iz3VC.js", _binary_assets_chunk_MOJQB5TN_9L_iz3VC_js_start, 0, "application/javascript"},
    {"/assets/chunk-RYQCIY6F-D6X7TqLO.js", _binary_assets_chunk_RYQCIY6F_D6X7TqLO_js_start, 0, "application/javascript"},
    {"/assets/chunk-V7JOEXUC-Yo1-V0uS.js", _binary_assets_chunk_V7JOEXUC_Yo1_V0uS_js_start, 0, "application/javascript"},
    {"/assets/chunk-VR4S4FIN-awYWJFZo.js", _binary_assets_chunk_VR4S4FIN_awYWJFZo_js_start, 0, "application/javascript"},
    {"/assets/chunk-XXDRQBXY-D7pYMXfx.js", _binary_assets_chunk_XXDRQBXY_D7pYMXfx_js_start, 0, "application/javascript"},
    {"/assets/classDiagram-OUVF2IWQ-ChzQG6bQ.js", _binary_assets_classDiagram_OUVF2IWQ_ChzQG6bQ_js_start, 0, "application/javascript"},
    {"/assets/classDiagram-v2-EOCWNBFH-ChzQG6bQ.js", _binary_assets_classDiagram_v2_EOCWNBFH_ChzQG6bQ_js_start, 0, "application/javascript"},
    {"/assets/cose-bilkent-JH36ORCC-Cg1Tn6Ix.js", _binary_assets_cose_bilkent_JH36ORCC_Cg1Tn6Ix_js_start, 0, "application/javascript"},
    {"/assets/cynefinDiagram-TSTJHNR4-Dqx3MYSd.js", _binary_assets_cynefinDiagram_TSTJHNR4_Dqx3MYSd_js_start, 0, "application/javascript"},
    {"/assets/cynefin-VYW2F7L2-BSmXNjHD.js", _binary_assets_cynefin_VYW2F7L2_BSmXNjHD_js_start, 0, "application/javascript"},
    {"/assets/cytoscape.esm-DTSO7Bv0.js", _binary_assets_cytoscape_esm_DTSO7Bv0_js_start, 0, "application/javascript"},
    {"/assets/dagre-VKFMJZFB-Dc8OyQR-.js", _binary_assets_dagre_VKFMJZFB_Dc8OyQR__js_start, 0, "application/javascript"},
    {"/assets/defaultLocale-DX6XiGOO.js", _binary_assets_defaultLocale_DX6XiGOO_js_start, 0, "application/javascript"},
    {"/assets/diagram-FQU43EPY-BAjgu-57.js", _binary_assets_diagram_FQU43EPY_BAjgu_57_js_start, 0, "application/javascript"},
    {"/assets/diagram-G47NLZAW-D55Isr_m.js", _binary_assets_diagram_G47NLZAW_D55Isr_m_js_start, 0, "application/javascript"},
    {"/assets/diagram-NH7WQ7WH-DNd0VJ_m.js", _binary_assets_diagram_NH7WQ7WH_DNd0VJ_m_js_start, 0, "application/javascript"},
    {"/assets/diagram-OA4YK3LP-DgyAjoFf.js", _binary_assets_diagram_OA4YK3LP_DgyAjoFf_js_start, 0, "application/javascript"},
    {"/assets/diagram-WEI45ONY-rJ2jqWd2.js", _binary_assets_diagram_WEI45ONY_rJ2jqWd2_js_start, 0, "application/javascript"},
    {"/assets/ebnfDiagram-CCIWWBDH-Cgd4-fJ7.js", _binary_assets_ebnfDiagram_CCIWWBDH_Cgd4_fJ7_js_start, 0, "application/javascript"},
    {"/assets/erDiagram-Q63AITRT-CWuotk-y.js", _binary_assets_erDiagram_Q63AITRT_CWuotk_y_js_start, 0, "application/javascript"},
    {"/assets/flowDiagram-23GEKE2U-2cZ1-br-.js", _binary_assets_flowDiagram_23GEKE2U_2cZ1_br__js_start, 0, "application/javascript"},
    {"/assets/ganttDiagram-NO4QXBWP-B9vgELs0.js", _binary_assets_ganttDiagram_NO4QXBWP_B9vgELs0_js_start, 0, "application/javascript"},
    {"/assets/gitGraphDiagram-IHSO6WYX-ClXJiEjU.js", _binary_assets_gitGraphDiagram_IHSO6WYX_ClXJiEjU_js_start, 0, "application/javascript"},
    {"/assets/graph-C9eacEi8.js", _binary_assets_graph_C9eacEi8_js_start, 0, "application/javascript"},
    {"/assets/index-B4D0ZKgB.css", _binary_assets_index_B4D0ZKgB_css_start, 0, "text/css"},
    {"/assets/index-BWsasQSj.js", _binary_assets_index_BWsasQSj_js_start, 0, "application/javascript"},
    {"/assets/infoDiagram-FWYZ7A6U-Cq3vOebR.js", _binary_assets_infoDiagram_FWYZ7A6U_Cq3vOebR_js_start, 0, "application/javascript"},
    {"/assets/init-Gi6I4Gst.js", _binary_assets_init_Gi6I4Gst_js_start, 0, "application/javascript"},
    {"/assets/ishikawaDiagram-FXEZZL3T-BVqTp7p5.js", _binary_assets_ishikawaDiagram_FXEZZL3T_BVqTp7p5_js_start, 0, "application/javascript"},
    {"/assets/journeyDiagram-5HDEW3XC-DkuAasZQ.js", _binary_assets_journeyDiagram_5HDEW3XC_DkuAasZQ_js_start, 0, "application/javascript"},
    {"/assets/kanban-definition-HUTT4EX6-B1-0DUb_.js", _binary_assets_kanban_definition_HUTT4EX6_B1_0DUb__js_start, 0, "application/javascript"},
    {"/assets/katex-C5jXJg4s.js", _binary_assets_katex_C5jXJg4s_js_start, 0, "application/javascript"},
    {"/assets/layout-DEXfKzaS.js", _binary_assets_layout_DEXfKzaS_js_start, 0, "application/javascript"},
    {"/assets/linear-nyeScZjw.js", _binary_assets_linear_nyeScZjw_js_start, 0, "application/javascript"},
    {"/assets/map-Czzmt4hB.js", _binary_assets_map_Czzmt4hB_js_start, 0, "application/javascript"},
    {"/assets/mindmap-definition-LN4V7U3C-CRSf194R.js", _binary_assets_mindmap_definition_LN4V7U3C_CRSf194R_js_start, 0, "application/javascript"},
    {"/assets/ordinal-Cboi1Yqb.js", _binary_assets_ordinal_Cboi1Yqb_js_start, 0, "application/javascript"},
    {"/assets/pegDiagram-2B236MQR-BcO2h6Jx.js", _binary_assets_pegDiagram_2B236MQR_BcO2h6Jx_js_start, 0, "application/javascript"},
    {"/assets/pieDiagram-ENE6RG2P-BuSjvKsW.js", _binary_assets_pieDiagram_ENE6RG2P_BuSjvKsW_js_start, 0, "application/javascript"},
    {"/assets/quadrantDiagram-ABIIQ3AL-DYIHCjpZ.js", _binary_assets_quadrantDiagram_ABIIQ3AL_DYIHCjpZ_js_start, 0, "application/javascript"},
    {"/assets/railroadDiagram-RFXS5EU6-TyxOBVs6.js", _binary_assets_railroadDiagram_RFXS5EU6_TyxOBVs6_js_start, 0, "application/javascript"},
    {"/assets/requirementDiagram-TGXJPOKE-DK7YXeJM.js", _binary_assets_requirementDiagram_TGXJPOKE_DK7YXeJM_js_start, 0, "application/javascript"},
    {"/assets/sankeyDiagram-HTMAVEWB-mWQtOzDn.js", _binary_assets_sankeyDiagram_HTMAVEWB_mWQtOzDn_js_start, 0, "application/javascript"},
    {"/assets/sequenceDiagram-DBY2YBRQ-BZbYj7tV.js", _binary_assets_sequenceDiagram_DBY2YBRQ_BZbYj7tV_js_start, 0, "application/javascript"},
    {"/assets/sizeCapture-X5ZJPWSS-DRWwrWzE.js", _binary_assets_sizeCapture_X5ZJPWSS_DRWwrWzE_js_start, 0, "application/javascript"},
    {"/assets/stateDiagram-2N3HPSRC-LENvSDk0.js", _binary_assets_stateDiagram_2N3HPSRC_LENvSDk0_js_start, 0, "application/javascript"},
    {"/assets/stateDiagram-v2-6OUMAXLB-CGvSjJgt.js", _binary_assets_stateDiagram_v2_6OUMAXLB_CGvSjJgt_js_start, 0, "application/javascript"},
    {"/assets/swimlanes-5IMT3BWC-Dlb7vtlK.js", _binary_assets_swimlanes_5IMT3BWC_Dlb7vtlK_js_start, 0, "application/javascript"},
    {"/assets/swimlanesDiagram-G3AALYLV-CN7h3I3y.js", _binary_assets_swimlanesDiagram_G3AALYLV_CN7h3I3y_js_start, 0, "application/javascript"},
    {"/assets/timeline-definition-FHXFAJF6-0O92i0Jd.js", _binary_assets_timeline_definition_FHXFAJF6_0O92i0Jd_js_start, 0, "application/javascript"},
    {"/assets/vennDiagram-L72KCM5P-CMpVF7tE.js", _binary_assets_vennDiagram_L72KCM5P_CMpVF7tE_js_start, 0, "application/javascript"},
    {"/assets/wardleyDiagram-EHGQE667-_1au6CfY.js", _binary_assets_wardleyDiagram_EHGQE667__1au6CfY_js_start, 0, "application/javascript"},
    {"/assets/xychartDiagram-FW5EYKEG-BUn214Ut.js", _binary_assets_xychartDiagram_FW5EYKEG_BUn214Ut_js_start, 0, "application/javascript"},
    {"/index.html", _binary_index_html_start, 0, "text/html"},
};
const int CBM_EMBEDDED_FILE_COUNT = 65;

static void __attribute__((constructor)) init_embedded_sizes(void) {
    cbm_embedded_file_t *files = CBM_EMBEDDED_FILES;
    files[0].size = (unsigned int)(_binary_assets_abnfDiagram_VRR7QNED__c_2PTVo_js_end - _binary_assets_abnfDiagram_VRR7QNED__c_2PTVo_js_start);
    files[1].size = (unsigned int)(_binary_assets_arc_C3M3wQW8_js_end - _binary_assets_arc_C3M3wQW8_js_start);
    files[2].size = (unsigned int)(_binary_assets_architectureDiagram_ZJ3FMSHR_F6b7AjI6_js_end - _binary_assets_architectureDiagram_ZJ3FMSHR_F6b7AjI6_js_start);
    files[3].size = (unsigned int)(_binary_assets_blockDiagram_677ZJIJ3_BRs5fZRQ_js_end - _binary_assets_blockDiagram_677ZJIJ3_BRs5fZRQ_js_start);
    files[4].size = (unsigned int)(_binary_assets_c4Diagram_LMCZKHZV_CIkMNFUy_js_end - _binary_assets_c4Diagram_LMCZKHZV_CIkMNFUy_js_start);
    files[5].size = (unsigned int)(_binary_assets_channel_KI9yzJ2z_js_end - _binary_assets_channel_KI9yzJ2z_js_start);
    files[6].size = (unsigned int)(_binary_assets_chunk_2Q5K7J3B_CBANiLPS_js_end - _binary_assets_chunk_2Q5K7J3B_CBANiLPS_js_start);
    files[7].size = (unsigned int)(_binary_assets_chunk_32BRIVSS_Dl_O1X_9_js_end - _binary_assets_chunk_32BRIVSS_Dl_O1X_9_js_start);
    files[8].size = (unsigned int)(_binary_assets_chunk_5VM5RSS4_CrsYnroW_js_end - _binary_assets_chunk_5VM5RSS4_CrsYnroW_js_start);
    files[9].size = (unsigned int)(_binary_assets_chunk_EX3LRPZG_CSLHLFEq_js_end - _binary_assets_chunk_EX3LRPZG_CSLHLFEq_js_start);
    files[10].size = (unsigned int)(_binary_assets_chunk_JWPE2WC7_BuYoJmxh_js_end - _binary_assets_chunk_JWPE2WC7_BuYoJmxh_js_start);
    files[11].size = (unsigned int)(_binary_assets_chunk_MOJQB5TN_9L_iz3VC_js_end - _binary_assets_chunk_MOJQB5TN_9L_iz3VC_js_start);
    files[12].size = (unsigned int)(_binary_assets_chunk_RYQCIY6F_D6X7TqLO_js_end - _binary_assets_chunk_RYQCIY6F_D6X7TqLO_js_start);
    files[13].size = (unsigned int)(_binary_assets_chunk_V7JOEXUC_Yo1_V0uS_js_end - _binary_assets_chunk_V7JOEXUC_Yo1_V0uS_js_start);
    files[14].size = (unsigned int)(_binary_assets_chunk_VR4S4FIN_awYWJFZo_js_end - _binary_assets_chunk_VR4S4FIN_awYWJFZo_js_start);
    files[15].size = (unsigned int)(_binary_assets_chunk_XXDRQBXY_D7pYMXfx_js_end - _binary_assets_chunk_XXDRQBXY_D7pYMXfx_js_start);
    files[16].size = (unsigned int)(_binary_assets_classDiagram_OUVF2IWQ_ChzQG6bQ_js_end - _binary_assets_classDiagram_OUVF2IWQ_ChzQG6bQ_js_start);
    files[17].size = (unsigned int)(_binary_assets_classDiagram_v2_EOCWNBFH_ChzQG6bQ_js_end - _binary_assets_classDiagram_v2_EOCWNBFH_ChzQG6bQ_js_start);
    files[18].size = (unsigned int)(_binary_assets_cose_bilkent_JH36ORCC_Cg1Tn6Ix_js_end - _binary_assets_cose_bilkent_JH36ORCC_Cg1Tn6Ix_js_start);
    files[19].size = (unsigned int)(_binary_assets_cynefinDiagram_TSTJHNR4_Dqx3MYSd_js_end - _binary_assets_cynefinDiagram_TSTJHNR4_Dqx3MYSd_js_start);
    files[20].size = (unsigned int)(_binary_assets_cynefin_VYW2F7L2_BSmXNjHD_js_end - _binary_assets_cynefin_VYW2F7L2_BSmXNjHD_js_start);
    files[21].size = (unsigned int)(_binary_assets_cytoscape_esm_DTSO7Bv0_js_end - _binary_assets_cytoscape_esm_DTSO7Bv0_js_start);
    files[22].size = (unsigned int)(_binary_assets_dagre_VKFMJZFB_Dc8OyQR__js_end - _binary_assets_dagre_VKFMJZFB_Dc8OyQR__js_start);
    files[23].size = (unsigned int)(_binary_assets_defaultLocale_DX6XiGOO_js_end - _binary_assets_defaultLocale_DX6XiGOO_js_start);
    files[24].size = (unsigned int)(_binary_assets_diagram_FQU43EPY_BAjgu_57_js_end - _binary_assets_diagram_FQU43EPY_BAjgu_57_js_start);
    files[25].size = (unsigned int)(_binary_assets_diagram_G47NLZAW_D55Isr_m_js_end - _binary_assets_diagram_G47NLZAW_D55Isr_m_js_start);
    files[26].size = (unsigned int)(_binary_assets_diagram_NH7WQ7WH_DNd0VJ_m_js_end - _binary_assets_diagram_NH7WQ7WH_DNd0VJ_m_js_start);
    files[27].size = (unsigned int)(_binary_assets_diagram_OA4YK3LP_DgyAjoFf_js_end - _binary_assets_diagram_OA4YK3LP_DgyAjoFf_js_start);
    files[28].size = (unsigned int)(_binary_assets_diagram_WEI45ONY_rJ2jqWd2_js_end - _binary_assets_diagram_WEI45ONY_rJ2jqWd2_js_start);
    files[29].size = (unsigned int)(_binary_assets_ebnfDiagram_CCIWWBDH_Cgd4_fJ7_js_end - _binary_assets_ebnfDiagram_CCIWWBDH_Cgd4_fJ7_js_start);
    files[30].size = (unsigned int)(_binary_assets_erDiagram_Q63AITRT_CWuotk_y_js_end - _binary_assets_erDiagram_Q63AITRT_CWuotk_y_js_start);
    files[31].size = (unsigned int)(_binary_assets_flowDiagram_23GEKE2U_2cZ1_br__js_end - _binary_assets_flowDiagram_23GEKE2U_2cZ1_br__js_start);
    files[32].size = (unsigned int)(_binary_assets_ganttDiagram_NO4QXBWP_B9vgELs0_js_end - _binary_assets_ganttDiagram_NO4QXBWP_B9vgELs0_js_start);
    files[33].size = (unsigned int)(_binary_assets_gitGraphDiagram_IHSO6WYX_ClXJiEjU_js_end - _binary_assets_gitGraphDiagram_IHSO6WYX_ClXJiEjU_js_start);
    files[34].size = (unsigned int)(_binary_assets_graph_C9eacEi8_js_end - _binary_assets_graph_C9eacEi8_js_start);
    files[35].size = (unsigned int)(_binary_assets_index_B4D0ZKgB_css_end - _binary_assets_index_B4D0ZKgB_css_start);
    files[36].size = (unsigned int)(_binary_assets_index_BWsasQSj_js_end - _binary_assets_index_BWsasQSj_js_start);
    files[37].size = (unsigned int)(_binary_assets_infoDiagram_FWYZ7A6U_Cq3vOebR_js_end - _binary_assets_infoDiagram_FWYZ7A6U_Cq3vOebR_js_start);
    files[38].size = (unsigned int)(_binary_assets_init_Gi6I4Gst_js_end - _binary_assets_init_Gi6I4Gst_js_start);
    files[39].size = (unsigned int)(_binary_assets_ishikawaDiagram_FXEZZL3T_BVqTp7p5_js_end - _binary_assets_ishikawaDiagram_FXEZZL3T_BVqTp7p5_js_start);
    files[40].size = (unsigned int)(_binary_assets_journeyDiagram_5HDEW3XC_DkuAasZQ_js_end - _binary_assets_journeyDiagram_5HDEW3XC_DkuAasZQ_js_start);
    files[41].size = (unsigned int)(_binary_assets_kanban_definition_HUTT4EX6_B1_0DUb__js_end - _binary_assets_kanban_definition_HUTT4EX6_B1_0DUb__js_start);
    files[42].size = (unsigned int)(_binary_assets_katex_C5jXJg4s_js_end - _binary_assets_katex_C5jXJg4s_js_start);
    files[43].size = (unsigned int)(_binary_assets_layout_DEXfKzaS_js_end - _binary_assets_layout_DEXfKzaS_js_start);
    files[44].size = (unsigned int)(_binary_assets_linear_nyeScZjw_js_end - _binary_assets_linear_nyeScZjw_js_start);
    files[45].size = (unsigned int)(_binary_assets_map_Czzmt4hB_js_end - _binary_assets_map_Czzmt4hB_js_start);
    files[46].size = (unsigned int)(_binary_assets_mindmap_definition_LN4V7U3C_CRSf194R_js_end - _binary_assets_mindmap_definition_LN4V7U3C_CRSf194R_js_start);
    files[47].size = (unsigned int)(_binary_assets_ordinal_Cboi1Yqb_js_end - _binary_assets_ordinal_Cboi1Yqb_js_start);
    files[48].size = (unsigned int)(_binary_assets_pegDiagram_2B236MQR_BcO2h6Jx_js_end - _binary_assets_pegDiagram_2B236MQR_BcO2h6Jx_js_start);
    files[49].size = (unsigned int)(_binary_assets_pieDiagram_ENE6RG2P_BuSjvKsW_js_end - _binary_assets_pieDiagram_ENE6RG2P_BuSjvKsW_js_start);
    files[50].size = (unsigned int)(_binary_assets_quadrantDiagram_ABIIQ3AL_DYIHCjpZ_js_end - _binary_assets_quadrantDiagram_ABIIQ3AL_DYIHCjpZ_js_start);
    files[51].size = (unsigned int)(_binary_assets_railroadDiagram_RFXS5EU6_TyxOBVs6_js_end - _binary_assets_railroadDiagram_RFXS5EU6_TyxOBVs6_js_start);
    files[52].size = (unsigned int)(_binary_assets_requirementDiagram_TGXJPOKE_DK7YXeJM_js_end - _binary_assets_requirementDiagram_TGXJPOKE_DK7YXeJM_js_start);
    files[53].size = (unsigned int)(_binary_assets_sankeyDiagram_HTMAVEWB_mWQtOzDn_js_end - _binary_assets_sankeyDiagram_HTMAVEWB_mWQtOzDn_js_start);
    files[54].size = (unsigned int)(_binary_assets_sequenceDiagram_DBY2YBRQ_BZbYj7tV_js_end - _binary_assets_sequenceDiagram_DBY2YBRQ_BZbYj7tV_js_start);
    files[55].size = (unsigned int)(_binary_assets_sizeCapture_X5ZJPWSS_DRWwrWzE_js_end - _binary_assets_sizeCapture_X5ZJPWSS_DRWwrWzE_js_start);
    files[56].size = (unsigned int)(_binary_assets_stateDiagram_2N3HPSRC_LENvSDk0_js_end - _binary_assets_stateDiagram_2N3HPSRC_LENvSDk0_js_start);
    files[57].size = (unsigned int)(_binary_assets_stateDiagram_v2_6OUMAXLB_CGvSjJgt_js_end - _binary_assets_stateDiagram_v2_6OUMAXLB_CGvSjJgt_js_start);
    files[58].size = (unsigned int)(_binary_assets_swimlanes_5IMT3BWC_Dlb7vtlK_js_end - _binary_assets_swimlanes_5IMT3BWC_Dlb7vtlK_js_start);
    files[59].size = (unsigned int)(_binary_assets_swimlanesDiagram_G3AALYLV_CN7h3I3y_js_end - _binary_assets_swimlanesDiagram_G3AALYLV_CN7h3I3y_js_start);
    files[60].size = (unsigned int)(_binary_assets_timeline_definition_FHXFAJF6_0O92i0Jd_js_end - _binary_assets_timeline_definition_FHXFAJF6_0O92i0Jd_js_start);
    files[61].size = (unsigned int)(_binary_assets_vennDiagram_L72KCM5P_CMpVF7tE_js_end - _binary_assets_vennDiagram_L72KCM5P_CMpVF7tE_js_start);
    files[62].size = (unsigned int)(_binary_assets_wardleyDiagram_EHGQE667__1au6CfY_js_end - _binary_assets_wardleyDiagram_EHGQE667__1au6CfY_js_start);
    files[63].size = (unsigned int)(_binary_assets_xychartDiagram_FW5EYKEG_BUn214Ut_js_end - _binary_assets_xychartDiagram_FW5EYKEG_BUn214Ut_js_start);
    files[64].size = (unsigned int)(_binary_index_html_end - _binary_index_html_start);
}

const cbm_embedded_file_t *cbm_embedded_lookup(const char *path) {
    for (int i = 0; i < CBM_EMBEDDED_FILE_COUNT; i++) {
        if (strcmp(CBM_EMBEDDED_FILES[i].path, path) == 0) {
            return &CBM_EMBEDDED_FILES[i];
        }
    }
    return NULL;
}
